import { Tables } from '@/types/database.types'

export type Mantenimiento = Tables<'mantenimientos'>

export const TIPOS_SERVICIO = [
  'Cambio de aceite',
  'Cambio de filtro de aceite',
  'Cambio de filtro de aire',
  'Revisión de frenos',
  'Cambio de pastillas de freno',
  'Cambio de líquido de frenos',
  'Cambio de cadena y piñones',
  'Cambio de kit de arrastre',
  'Cambio de piñones',
  'Cambio de neumáticos',
  'Revisión de bujías',
  'Ajuste de válvulas',
  'Ajuste de balancines',
  'Revisión de rodamientos',
  'Engrase de ejes',
  'Revisión de suspensiones',
  'Cambio de aceite de horquilla',
  'Revisión de embrague',
  'Ajuste de embrague',
  'Lubricación de guayas',
  'Revisión de cables',
  'Revisión de batería',
  'Carga de batería',
  'Revisión de luces y fusibles',
  'Revisión de sistema de carga',
  'Revisión de estator',
  'Limpieza de inyectores',
  'Limpieza de carburador',
  'Revisión general',
  'Otro',
] as const
